### ISSUE TITLE
Unable to use production URL

### ISSUE THREAD

**Issue by ashwin0003** [mxenabled/atrium-php#23]
Hi,

I have been using the package with dev-url and test-members, which worked without a hitch. Was able to retrieve Member, accounts and transactions for the test-member.

Then I try a regular member with dev-url, member and account got synced but I'm not getting transactions.
Any thoughts on transactions for regular-member with dev-url?

So I tried production-url which hasn't worked out.
Extract from my service provider.
```php
                /*
                $env = App::environment();
                $baseURL = $env === 'prod' || $env === 'production'
                    ? 'https://atrium.mx.com'
                    : 'https://vestibule.mx.com';
                 */
                $baseURL = 'https://atrium.mx.com';
                $guzzle = new GuzzleClient([ 'base_uri' => $baseURL ]);

                return new AtriumClient($apiKey, $clientId, $guzzle);
```
Exception
```php
Exception with message 'Atrium Sync Error when syncing Members: [401] Client error: `GET https://vestibule.mx.com/users/USR-13fa1846-d9e9-4aab-8d7d-47a538b9b56f/members?page=1&records_per_page=25` resulted in a `401 Unauthorized` response:
{"error":{"message":"Invalid MX-API-KEY or MX-CLIENT-ID header"}}
'
```
As you can see it's still trying to use dev-url.
Anything I'm doing wrong while specifying the url?

**Comment by brettmortensen** [comment]
@ashwin0003 Thank you for reaching out.

Development (vestibule) GUIDs cannot be used in the production environment. So we will want to stick with the default `https://vestibule.mx.com` environment here.

Our team would be happy to dive in and troubleshoot why transactions are not being returned. Due to the nature of aggregation, we generally need more information. We use the https://atriumsupport.zendesk.com platform to gather information and correspond on these type of issues. Please login via that platform, create a ticket, and our team will investigate as soon as possible.

**Comment by ashwin0003** [comment]
@brettmortensen Thank you for the fast reply.

Please look at the service provider code I pasted in the first post.
My issue with environment is despite specifying production url(atrium.mx.com), the api calls are being made to development url(vestibule)

![Screenshot from 2020-12-03 00-23-02_1](https://user-images.githubusercontent.com/16756579/100919106-60301200-34ff-11eb-9809-be68c64860d3.png)

**Comment by brettmortensen** [comment]
In order to set the environment to production you can set the configuration as follows:
```
atrium\Configuration::getDefaultConfiguration()->setHost('https://atrium.mx.com');
$client = new atrium\Api\AtriumClient(
    "YOUR_API_KEY",
    "YOUR_CLIENT_ID",
    new GuzzleHttp\Client()
);
```

**Comment by ashwin0003** [comment]
@brettmortensen Many many thanks. This has got be the fastest I have ever received a solution.

```php
Exception with message 'Atrium Error while adding user: [403] Client error: `POST https://atrium.mx.com/users` resulted in a `403 Forbidden` response'
```
A matter of whitelisting ip address which I can handle in the morning but more importantly I have production URL, thanks to you.



BTW, I have been using this package for almost 2 weeks and I have become a big fan of how you guys have implemented this. Personally, the attribute-getters in models and the abundance of helper functions, have been putting a smile on my face. Clean.

Do add this info to the readme.md of the package, I guess in the `Example Usage` section.
