### ISSUE TITLE
Unable to connect to API using library from packagist

### ISSUE THREAD

**Issue by dannyYassine** [mxenabled/atrium-php#26]
Hi there,

I downloaded the library from packagist directly using:

```
composer require mxenabled/atrium-php
```

Then following the directions on the packagist's README, I have:

```php
$client = new AtriumClient(
    'vestibule.mx.com', // the dev env.
    '<api_key>',
    '<client_id>'
);

$user = [
    'id' => '1',
    'is_disabled' => false,
    'email' => 'danny@email.com',
    'metadata' => 'Yada yada yada'
];

$response = $client->createUser($user);
```

While debugging the response I am getting is the following:

```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 08 Feb 2021 16:13:09 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Location: https://vestibule.mx.com:443/users
Strict-Transport-Security: max-age=31536000
Allow: GET, PUT, POST, DELETE, HEAD, OPTIONS

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

As well, I looked at the documentation for [authentication](https://docs.mx.com/api/guides/introduction#authentication_and_security), the source code from the library does not match the authentication procedure as defined from the website documentation.

For example, in the source code, I see we are simply adding the api_key and client_id keys to the header,

```
curl_setopt(
      $request, CURLOPT_HTTPHEADER, [
      'Accept: application/vnd.mx.atrium.v1+json',
      'Content-Type: application/json',
      "MX-API-Key: {$this->mx_api_key}",
      "MX-Client-ID: {$this->mx_client_id}"
  ]
  );
```

where as in the docs, its a base 64 encoding of their combination:

```
Authentication: Beader <base_64_of:{client_id}:{api_key}>
```

I am currently blocked from integrating your library to our app. Let me know what is the expected procedure I need to follow.

Thank you for your time and help.

**Comment by brettmortensen** [comment]
Hi @dannyYassine , thanks for reaching out.

Our "Atrium" libraries are not compatible with the "MX Platform API" documentation you linked to above. Atrium is an older API that we still support, but we are no longer accepting new registrations. The MX Platform API is our latest API, but unfortunately we do not have any wrapper libraries at this time.

**Comment by dannyYassine** [comment]
Hey @brettmortensen , thanks for the quick response!

If you do create a php library for the MX Platform API, please let me know! thanks :)

**Comment by createbyte** [comment]
Will there be a wrapper in the near future?

**Comment by brettmortensen** [comment]
Thanks for reaching out @createbyte! A PHP wrapper is something that we are considering, but do not have any timelines at the moment.
