### ISSUE TITLE
Installation instruction do not work

### ISSUE THREAD

**Issue by vamsee-gomatam** [mxenabled/atrium-php#8]
I have updated my `composer.json` as instructed in the README. I still end up with a fork of this repository (https://github.com/shubinmi/atrium-php) which is a year behind on development.

Actual working instructions to install this library via composer would be greatly appreciated.

**Comment by brettmortensen** [comment]
Thank you @vamsee-gomatam for pointing this out 👍 

I have updated the composer config file. Following the README instructions should now install the latest version of this library correctly.

**Comment by vamsee-gomatam** [comment]
Works like a charm now. Thanks for the quick fix 👍
